static_d405:
  exposure: 100
  flip_mode: false
  fps: 30
  gain: 31
  id: "218622277783"
  resolution: 1080p
wrist_d435:
  exposure: 67
  flip_mode: true
  fps: 30
  gain: 28
  id: "819612070593"
  resolution: 720p
